- name: setup frontend
  hosts: localhost
  become: yes
  tasks:
    - name: install Nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: start and enable frontend service
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes

    - name: download frontend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
        dest: /tmp/frontend.zip

    - name: unzip frontend code
      ansible.builtin.unarchive:
        src: /tmp/frontend.zip # by default checks in ansible server
        dest: /usr/share/nginx/html
        remote_src: yes

    - name: copy backend service
      ansible.builtin.copy:
        src: frontend.service
        dest: /etc/nginx/default.d/expense.conf

    - name: Restart Nginx Service
      ansible.builtin.service:
        name: nginx
        state: restarted
